refactor editconf, some i3 conf changes

diff --git a/scripts/editconf b/scripts/editconf
--- a/scripts/editconf
+++ b/scripts/editconf
@@ -1,58 +1,51 @@
 #!/bin/bash
+
 usage="Edit or generate shortcutted config files.\n\
 Usage:\n\
-	editconf [options] [shortcut_name]\n\
+	editconf [options] [shortcut_names...]\n\
 Options:\n\
 	-g, --generate          generate shortcuts for other programs\n\
-	-p, --program PROGRAM   open shortcut_name in PROGRAM\n\
+	-p, --program PROGRAM   open shortcut_name(s) in PROGRAM\n\
 	-l, --list              list available shortcut shortcut names\n\
 	-h, --help              show this help message\n\
 \n\
-With no parameters, open shortcut_name in neovim"
+With no parameters, open shortcut_name(s) in neovim"
 
-
+shortcuts_file=~/scripts/shortcuts
 
 generate_shortcuts() {
 	vim_file="$HOME/.config/nvim/shortcuts.vim"
 	rm -f $vim_file
 	echo "let g:my_shortcuts = {" > $vim_file
-
-	for shortcut in "${shortcuts_array[@]}"; do
-		read name path <<< "$shortcut"
-		printf "	\\ '%s': '%s',\n" $name $path >> $vim_file
-	done
-
+	echo "$shortcuts" | sed "s/^\(.*\)\s\+\(.*\)$/	\\\\ '\1': '\2',/" >> $vim_file
 	echo "\ }" >> $vim_file
+
 	echo "Successfully generated shortcuts."
 }
 
 # Argument 1: program to open with
-# Argument 2: shortcut name
+# Argument 2+: shortcut names
 open_shortcut() {
-	for shortcut in "${shortcuts_array[@]}"; do
-		read name path <<< "$shortcut"
-		if [[ $name == $2 ]]; then
-			eval "$1 $path"
-			return
-		fi
+	paths=()
+	for shortcut_name in ${@:2}; do
+		path=$(echo "$shortcuts" | grep "^$shortcut_name\\s" | cut -f2)
+		[[ -n "$path" ]] && paths+=("$path") || echo "Could not find shortcut $shortcut_name."
 	done
-	echo "Shortcut $2 not found"
+	if [[ -n "$paths" ]]; then
+		eval "$1 ${paths[@]}"
+	else
+		echo "No valid shortcuts given, exiting."
+	fi
 }
 
-list_shortcuts() {
-	for shortcut in "${shortcuts_array[@]}"; do
-		cut -f1 <<< $shortcut
-	done
-}
-
-readarray -t shortcuts_array < <(sed -e "/\(^\s*#\)\|\(^$\)/d" ~/scripts/shortcuts)
-
+shortcuts=$(sed "/\(^\s*#\)\|\(^$\)/d" $shortcuts_file)
 case $1 in
 	-g|--generate) generate_shortcuts ;;
-	-p|--program) open_shortcut $2 $3 ;;
+	-p|--program) open_shortcut $2 ${@:3} ;;
 	-h|--help) echo -e "$usage" ;;
-	-l|--list) list_shortcuts ;;
-	*) open_shortcut nvim $1;;
+	-l|--list) echo "$shortcuts" | cut -f1 ;;
+	*) open_shortcut nvim $@ ;;
 esac
 
+# vim: set ts=3 noet :
 
